server:
  port: 1011

eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:1010/eureka/

spring:
  application:
    name: my-config

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configs
#        git:
#          uri: https://github.com/renchao1990/configs.git
#          search-paths: '{application}'



